api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "credit-card-fee"
type = "function"
uid = "7b1d3d58-2bfd-a9ee-435d-7e59d8e58e0b762ec970"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
